FORMAT: 1A
HOST: http://www.google.com

# Hello
Hello API is a *greeting* service

# Group Notes
Notes related resources of the **Hello API**

## Grretings Collection [/greetings]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Hello", "name":"John"
        }, {
          "id": 2, "title": "Bonjour", "name":"Smith"
        }]


