FORMAT: 1A
HOST: http://localhost:9000

# Hello
Hello API is a *greeting* service

# Group Notes
Notes related resources of the **Hello API**

## Greetings Collection [/greetings]
### List all Notes [GET]
+ Response 200 (text/plain; charset=utf-8)
    
    + Headers
    
            content-length:5    

    + Body  
            
            "hello"
